#!/bin/bash
# Job name:
#SBATCH --job-name=subjkb_tuning
# dbamman faculty computing account
#SBATCH --account=fc_dbamman
# Partition:
#SBATCH --partition=savio2_gpu
#
# Wall clock limit: (this runs for 4 hrs max)
#SBATCH --time=04:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --gres=gpu:1
# run 5 iterations of the same model
#SBATCH --array=0-1
#
# Set email notifications
#SBATCH --mail-user=mashabelyi@berkeley.edu
#SBATCH --mail-type=all



source /global/home/users/mashabelyi/anaconda3/bin/activate /global/home/users/mashabelyi/anaconda3/envs/subjkb

python run.py --model transE --mode train-val --f --data /global/home/users/mashabelyi/subjkb/data/yelp2 --name /global/home/users/mashabelyi/subjkb/models/YELP2_transe_d100_m0.5_lr0.0001_n1 --num_epochs 200 --embedding_dim 100 --patience 10 --norm 1 --optim adam --learning_rate 0.0001 --margin 0.5

source /global/home/users/mashabelyi/anaconda3/bin/deactivate


# python run.py --model transE --mode train --data /global/home/users/mashabelyi/subjkb/data/yelp2 --name /global/home/users/mashabelyi/subjkb/models/YELP2_transe_d100_m0.5_lr0.0001_n1 --num_epochs 200 --embedding_dim 100 --patience 10 --norm 1 --optim adam --learning_rate 0.0001 --margin 0.5